ansys/pyedb

- src/pyedb/__init__.py
> MAINT: Bump version to 0.3.dev0

- src/pyedb/__init__.py
> MAINT: Bump version into 0.4.dev0

- src/pyedb/dotnet/edb_core/edb_data/hfss_simulation_setup_data.py
- tests/legacy/system/conftest.py
- tests/legacy/system/test_edb.py
This PR reverts commit 65d462a247deb32def93b43e8c0961502e5266b8.
> FIX: Temporary removal of 2024.1 feature

- tests/legacy/system/test_edb_modeler.py
> move polygon layer test added

- doc/source/getting_started/troubleshooting.rst
Our dependabot PR are blocked due to this doc style issue.
> DOC: Update doc file to pass doc style

- pyproject.toml
- src/pyedb/dotnet/edb_core/edb_data/primitives_data.py
- tests/legacy/system/test_edb_modeler.py
duplicate across layer function.
> duplicate across layers new function

- src/pyedb/__init__.py
> MAINT: Bump version into 0.6.dev0

- src/pyedb/__init__.py
Bumping dev version (should be merged after the release of version `0.6.0`)
> MAINT: Bump version into 0.7.dev0

- src/pyedb/__init__.py
Wait until https://github.com/ansys/pyedb/actions/runs/8457797407 completion.
> MAINT: Bump version into 0.8.dev0

- src/pyedb/generic/process.py
> siwave solve bug fix on Linux

- .github/workflows/ci_cd.yml
Past PR that got merged had title difficult to understand at first read and which didn't help to know what type of content would be released in the next new release. This should alleviate this burden to some extent.
> CI: Check PR title format

- doc/source/getting_started/installation.rst
- doc/source/getting_started/troubleshooting.rst
Some URL were using ansys-edb or pyansys-edb. This PR fixes that.
> DOC: Update wrong URLs

- pyproject.toml
- src/pyedb/dotnet/edb_core/edb_data/layer_data.py
- src/pyedb/dotnet/edb_core/materials.py
- src/pyedb/dotnet/edb_core/stackup.py
- tests/example_models/TEDB/stackup.json
- tests/example_models/TEDB/stackup_renamed.json
- tests/legacy/system/test_edb.py
- tests/legacy/system/test_edb_materials.py
- tests/legacy/unit/test_materials.py
This PR will refact the materials way of handling AMAT files and reading them.
Closes #360
> FEATURE: Create material from syslib

- .github/workflows/ci_cd.yml
As title says.
~> [!WARNING]~
~> This branch should not be merged until a new ansys/action release is performed.~
~Note: Leverage https://github.com/ansys/actions/issues/446 (which is not released yet but part of main version)~
> CI: Check title with ansys action

- src/pyedb/dotnet/edb_core/dotnet/database.py
- src/pyedb/edb_logger.py
- src/pyedb/generic/settings.py
Fix duplication of logger when Pyaedt logger is initialized.
> FIX: Logger

- src/pyedb/generic/settings.py
> FIX: Precommit by removing unused import

- pyproject.toml
- src/pyedb/dotnet/edb_core/padstack.py
- tests/legacy/system/test_edb_padstacks.py
Padstack instances query intersecting given bounding box using Rtree class.
> FEAT: Padstack instances query intersecting given bounding box using Rtree class.

- src/pyedb/__init__.py
Wait for 0.10.0 to be release before merging
> CHORE: Bump development version into 0.11.dev0

- examples/legacy_standalone/03_rename_nets_and_ports.py
Port and nets renaming example
> DOCS: Port and nets renaming example

- src/pyedb/dotnet/edb_core/layout.py
Adding bug fix caused by no layer assigned on primitives
closing #478
> FIX: primitive by layer crash with none object

- src/pyedb/configuration/cfg_pin_groups.py
> FIX: Logger typo fix

- src/pyedb/__init__.py
> CHORE: Bump dev version into 0.15.dev0

- src/pyedb/dotnet/edb_core/utilities/simulation_setup.py
Fixing bug on HFSSPI simulation setup creation.
> FIX: HFSSPI simulation setup creation

- doc/source/api/CoreEdb.rst
layout validation documentation exposed
> DOCS: layout validation documentation exposed

- src/pyedb/__init__.py
> CHORE: Bump dev version to 0.16.dev0

- src/pyedb/dotnet/edb_core/layout.py
Tons of warning on layers not present in stackup and the failure to add_profile because Outline is a non_stackup_layer
> FIX: Fixes 2 issues in ipc2581 exports.

- src/pyedb/dotnet/edb_core/edb_data/primitives_data.py
- src/pyedb/dotnet/edb_core/layout_validation.py
- tests/legacy/system/test_edb.py
- tests/legacy/system/test_edb_modeler.py
Added also a method in layout_validation.py to remove nets self intersections.
> FEAT: Added a new property to check if a polygon has self.intersections and  a method to remove it from the polygon.

- src/pyedb/__init__.py
As title says. Follows releasing of 0.19.0
> CHORE: Bump dev version into 0.20.dev0

- src/pyedb/dotnet/edb_core/edb_data/padstacks_data.py
Equation to lowest the circle is applied to rad 1 to respect shape of microvias from litterature.
With the current code the via was drawn like this
closing #682
> FIX: Change line 815 and 816.  Update the way 3D object is created

- src/pyedb/__init__.py
Do not merge until v0.23.0 is released.
> CHORE: Bump version into v0.24.dev0

- src/pyedb/__init__.py
Bumping dev version after the release of v0.24.0
> CHORE: Bump dev version into v0.25.dev0

- doc/source/conf.py
> FIX: Update logo

- pyproject.toml
> BUILD: Update numpy upper bound to <2.2

- examples/use_configuration/import_ports.py
- src/pyedb/configuration/configuration.py
- src/pyedb/dotnet/edb_core/edb_data/padstacks_data.py
- src/pyedb/siwave.py
- tests/legacy/system/test_edb_configuration_2p0.py
- bug fix #793 
- Better file path management in Siwave class
- typo fix in example
- Minor fix in configuration class
> FIX: padstack and siwave

- .github/workflows/ci_cd.yml
- tests/legacy/system/test_edb.py
- tests/legacy/system/test_edb_nets.py
> CI: Add job to test on Linux

- src/pyedb/dotnet/edb_core/nets.py
Speed up the edb plot method by reusing the layer color properties.
> FIX: Speedup Edb plot method

- .github/workflows/ci_cd.yml
This should fix the current release failure, see https://github.com/ansys/pyedb/actions/runs/11034547096/job/30653320620
> CI: Fix pyaedt test in linux

- .github/workflows/ci_cd.yml
> CI: Extend pyaedt testing timeout linux

- src/pyedb/dotnet/edb_core/nets.py
Add new optional argument to plot function
> FEAT: #850 : Add custom title argument to plot function

- AUTHORS
> CHORE: Update AUTHORS to match ansys

- src/pyedb/dotnet/edb_core/layout_validation.py
make the via naming convention the same as AEDT
> FIX: via name convention

- src/pyedb/__init__.py
Regular bump version after release
@svandenb-dev Please remember to do those changes for every major / minor release.
> CHORE: Bump dev version into 0.32.dev0

- doc/source/conf.py
- examples/use_configuration/import_sources.py
- examples/use_configuration/index.rst
Example is not link to web page
> FIX: example docs

- pyproject.toml
> BUILD: bump numpy upper limit to 3.X

- .github/workflows/ci_cd.yml
> CI: Fix release workflow

- .github/workflows/ci_cd.yml
> CI: Use renamed ansys action

- src/pyedb/__init__.py
> CHORE: Bump dev version into v0.38.dev0

- src/pyedb/grpc/database/primitive/primitive.py
- tests/conftest.py
This PR is fixing grpc test failing due to incorrect release version
> FIX: release fix

- .github/workflows/ci_cd.yml
> CI: Add mandatory inputs to deploy actions

- src/pyedb/__init__.py
@svandenb-dev Please, remember to bump the dev version every time you do a minor/major release :)
> CHORE: Update dev version

- src/pyedb/grpc/database/layout/layout.py
- src/pyedb/grpc/database/padstacks.py
- src/pyedb/grpc/database/primitive/padstack_instance.py
- tests/grpc/system/test_edb_layout.py
- tests/grpc/system/test_edb_padstacks.py
This PR is adding the code from PR#992 from grpc transition tracker.
@boyang2022 
PR #992
> FEAT: Grpc transition pr#992 tracker

- src/pyedb/__init__.py
> CHORE: Bump release 0.41.dev0

- src/pyedb/__init__.py
> CHORE: Bump release 0.42.dev0

- src/pyedb/dotnet/database/cell/terminal/padstack_instance_terminal.py
- src/pyedb/dotnet/database/cell/terminal/point_terminal.py
- src/pyedb/dotnet/database/cell/terminal/terminal.py
- tests/legacy/system/test_edb_configuration_2p0.py
- Move method location from Terminal class to PointTerminal  class
- Add new metho location to PadstackInstance class
> FIX: port location

- src/pyedb/dotnet/database/utilities/simulation_setup.py
- tests/legacy/system/test_edb_configuration_2p0.py
This PR fix the problem on setting on dicsrete sweep
> FIX: freq sweep type

- src/pyedb/dotnet/database/sim_setup_data/data/sweep_data.py
- src/pyedb/dotnet/database/utilities/simulation_setup.py
- tests/legacy/system/test_edb.py
1, new property frequency_string. 
2, refactored SweepData.add to improve robustness
> REFACTOR: freq sweep

- src/pyedb/dotnet/database/edb_data/padstacks_data.py
- tests/legacy/system/test_edb_padstacks.py
> REFACTOR: split via

- src/pyedb/grpc/database/definition/padstack_def.py
- src/pyedb/grpc/database/hierarchy/component.py
- src/pyedb/grpc/database/hierarchy/pingroup.py
- src/pyedb/grpc/database/layout/layout.py
- src/pyedb/grpc/database/modeler.py
- src/pyedb/grpc/database/primitive/bondwire.py
- src/pyedb/grpc/database/primitive/circle.py
- src/pyedb/grpc/database/primitive/padstack_instance.py
- src/pyedb/grpc/database/primitive/path.py
- src/pyedb/grpc/database/primitive/polygon.py
- src/pyedb/grpc/database/primitive/primitive.py
- src/pyedb/grpc/database/primitive/rectangle.py
- src/pyedb/grpc/database/source_excitations.py
- src/pyedb/grpc/database/terminal/bundle_terminal.py
- src/pyedb/grpc/database/terminal/edge_terminal.py
- src/pyedb/grpc/database/terminal/padstack_instance_terminal.py
- src/pyedb/grpc/database/terminal/pingroup_terminal.py
- src/pyedb/grpc/database/terminal/point_terminal.py
- src/pyedb/grpc/database/terminal/terminal.py
- src/pyedb/grpc/database/utility/hfss_extent_info.py
- src/pyedb/grpc/edb.py
Adjusts import paths in pyedb to keep them in sync with module path changes in ansys-edb-core version 0.2.0.dev3
> FIX: Fixed import paths for ansys-edb-core version 0.2.0.dev3

- src/pyedb/__init__.py
> CHORE: Bump release 0.45.dev0

- src/pyedb/dotnet/database/cell/primitive/path.py
- src/pyedb/dotnet/database/geometry/point_data.py
- src/pyedb/dotnet/database/geometry/polygon_data.py
- src/pyedb/dotnet/edb.py
- tests/legacy/system/test_edb_geometry.py
- tests/legacy/system/test_edb_layout.py
- new property Edb.pyedb_class
- new method get_center_line_polygon_data
- new methods under PointData and PolygonData
> FEAT: center line polygon data

- src/pyedb/configuration/cfg_modeler.py
- tests/legacy/system/test_edb_configuration_2p0.py
New feature in edb cfg
- delete primitives
> FEAT: delete primitives by cfg

- src/pyedb/grpc/database/hfss.py
- src/pyedb/grpc/database/simulation_setup/sweep_data.py
- src/pyedb/grpc/database/siwave.py
- tests/grpc/system/test_edb.py
Fixes unit tests that are failing due to a recent pyedb-core change in SweepData API
> FIX: Fix unit tests that failed due to recent pyedb-core change in SweepData API

- src/pyedb/__init__.py
> CHORE: Bump release 0.46.dev0

- src/pyedb/__init__.py
> CHORE: bump release 0.47.dev0

- src/pyedb/dotnet/database/utilities/siwave_simulation_setup.py
- tests/legacy/system/test_edb_configuration_2p0.py
This PR fix the problem on setting frequency sweep for SIwave
> FIX: SIwave Sweep

- src/pyedb/__init__.py
> CHORE: Bump release 0.50.dev0

- src/pyedb/configuration/cfg_ports_sources.py
- src/pyedb/configuration/configuration.py
- src/pyedb/dotnet/database/cell/layout.py
- src/pyedb/dotnet/database/dotnet/database.py
- src/pyedb/dotnet/database/layout_validation.py
- src/pyedb/dotnet/database/modeler.py
- src/pyedb/dotnet/edb.py
- add check for resistors and capacitors in layout validation
- revert grpc for edb config ports
- refactor edb to compute edb initialization time
- cache edb.layout.primitives
> FIX: layout_validation.py

- src/pyedb/configuration/configuration.py
- src/pyedb/dotnet/database/stackup.py
- revert grpc
- fix padstack definition after load stackup
> FIX: stackup load and grpc revert

- src/pyedb/grpc/database/components.py
This PR is improving Typing on Components class
> REFACTOR: components typing

- src/pyedb/__init__.py
> CHORE: Bump release 0.54.dev0

- tests/conftest.py
- tests/system/test_edb_configuration_2p0.py
This PR is adding test skipping for cfg file with grpc as it is not yet implemented.
> CHORE: skip tests on cfg file with grpc

- .github/workflows/ci_cd.yml
As title says.
Address #1401
Some thinking / a discussion should be started on how to avoid releasing pyedb and breaking pyaedt.
> CI: Extend pyedb testing

- src/pyedb/__init__.py
> CHORE: bump release 0.56.0

- src/pyedb/dotnet/edb.py
- src/pyedb/generic/design_types.py
- src/pyedb/generic/settings.py
This is to fix https://github.com/ansys/pyedb/issues/1399
> REFACTOR: Check installed versions

- src/pyedb/configuration/cfg_operations.py
- src/pyedb/configuration/configuration.py
Fix the bug introduced in previous PR. 
- extension crashes when exporting configure file
> FIX: cfg_operations.py

- src/pyedb/grpc/database/modeler.py
- src/pyedb/grpc/database/primitive/path.py
> FIX: issue 1511 fix

- src/pyedb/grpc/database/terminal/terminal.py
> FIX: issue 1514 -> to check

- doc/source/archive.rst
Update text description of DotNet deprecation.
> DOCS: Update archive.rst
