ansys/pyedb

.github/workflows/ci_cd.yml, pyproject.toml
Publishing to pypi got canceled because we had a dependency to pyedb-core.
This package is now named ansys-edb-core and available on pypi !
=> MAINT: Use ansys-edb-core dependency

.github/workflows/ci_cd.yml, pyproject.toml, src/pyedb/__init__.py, tests/test_warnings.py
This PR add python 3.7 as a valid python version for PyEDB. On top of that, the smoke tests have been added to increase the range of python version tested.
Since this python version has been added to allow users to install PyAEDT with version 3.7, a deprecated warning is triggered to notify the users of an incoming deprecation. This deprecated warning is tests.
=> MAINT: Add python 3 7 compatibility

.github/workflows/ci_cd.yml, pyproject.toml
Extend job of wheelhouse and smoke tests with python 3.11 (it wasn't part of the project classifiers).
Also add the extra step of smoke testing which is not yet present ....
=> CI: Extend wheelhouse and smoke tests

src/pyedb/dotnet/edb_core/edb_data/utilities.py, src/pyedb/dotnet/edb_core/layout.py, tests/legacy/system/test_edb.py
Fixing bug on occupying ratio with edb stats computation:
- implementation more accurate
- surface accounted for path and polygons
=> bugfix edb_stats occupying ratio per layer

src/pyedb/dotnet/edb_core/hfss.py, tests/legacy/system/test_edb.py
this is breaking method create_vertical_circuit_port_on_clipped_traces that is not tested in EDB but in PyAEDT.
Added unit tests
=> layer getter has changed and is now returning the Edb object

src/pyedb/dotnet/edb_core/stackup.py
As title says.
Note: previously, pre-commit wasn't blocking PR from being merged which explains why a PR got merged while pre-commit pr was failing. This is no longer possible.
=> CHORE: Fix precommit failure

doc/source/getting_started/about.rst
When trying to use the following documentation directive, we end up with an error when building the PDF file.
```
.. image:: https://images.ansys.com/is/image/ansys/ansys-electronics-technology-collage?wid=941&op_usm=0.9,1.0,20,0&fit=constrain,0
:width: 800
:alt: AEDT Applications
:target: https://www.ansys.com/products/electronics
```
It seems that the image URL is not standard (doesn't ends on png or other format file) which leads to an error.
Since it was just a reference to pyaedt, I propose to remove it for the moment.
**Note**: Another solution would be to save the file inside the repo and leverage this image later on. However, it will make the repo "heavier".
Closes #334
=> DOC: Remove non standard link to image

src/pyedb/dotnet/edb_core/stackup.py
Protect the import of matplotlib.colors in pyedb.dotnet.edb_core.stackup to avoid import errors when users install only the base dependency set, which does not include matplotlib.
Fixes #351
=> FIX: protect import from matplotlib

src/pyedb/dotnet/edb_core/edb_data/components_data.py
Fixing component zero value solder balls height setter. The bug was causing code skipping.
=> FIX: Zero_value_solder_ball_height

src/pyedb/dotnet/edb_core/materials.py, tests/legacy/system/test_edb_materials.py
Extend tests with `test_materials_load_material`.
On top of that, we avoid covering lines of code related to the use of the deprecated `loss_tangent`.
Closes #368
=> TEST: Materials load_material method

src/pyedb/dotnet/edb.py, tests/legacy/unit/test_edb.py
Remove AEDT project-related files on EDB open (e.g. file.aedt and/or file.aedt.lock for file.aedb) only if Edb constructor is run with isreadonly False and remove_existing_aedt True.
Fixes #412
=> FIX: Don't always remove AEDT project files

src/pyedb/dotnet/edb_core/materials.py, tests/legacy/system/test_edb_materials.py
This refactoring of the Materials classes aims at fixing the GUI interactions problems of #426.
Changes:
- Removal of the cache used to work with materials, the resulting approach heavily rely on the EDB API
- Check of material names to avoid ending with two materials with the same name in the GUI.
As a reminder, the GUI is case insensitive and is not able to distinguish two materials like "MatA" and "mata".
=> REFACTOR: Materials implementation

src/pyedb/dotnet/edb_core/stackup.py, tests/legacy/system/test_edb_stackup.py
There were two bugs that prevented to export a stackup into a JSON file:
- we were still using `_json_format` call which was removed when refactoring the materials;
- we were trying to serialize data that isn't, aka the "pedb" and edb object associated to each layer.
Closes #468
Note: depending on the use of `_json_format` used in the `stackup_layers` we might also want to rework (and/or rename) that method to avoid passing information that should be passed to our users.
=> FIX: Stackup export to JSON file

src/pyedb/dotnet/edb_core/edb_data/nets_data.py, src/pyedb/dotnet/edb_core/nets.py, src/pyedb/dotnet/edb_core/stackup.py, src/pyedb/generic/plot.py
Some plot related methods were using a `show` argument and this information was not propagated consistently on the other methods. Changes make it so. Also, the parameter of `plot_matplotlib` associated to the saving of the figure has been updated to be consistent with other plot methods, i.e. from argument `snapshot_path` to `save_plot`.
Note: to make things consistent with previous development, if one provides a path to save the figure. The figure won't be shown, even if argument show is set to True.
=> REFACTOR: Make plot consistent wrt show

.github/workflows/ci_cd.yml
Until we find a solution for the recurrent error with `matplotlib` happening when we run the tests on runner `pyedb-ci-1`, I propose we assign:
- documentation to `pyedb-ci-1`
- legacy tests to `pyedb-ci-0`
For this purpose I extended the labels associated to the runners, we might get rid of that later on. 
Partially address #516
=> CI: Temporary assign runner to jobs

.github/workflows/ci_cd.yml
Seems like some recent changes related to `plot` had a side effect on the test behavior.
This PR ensures that every job in CICD has environment variable `PYEDB_CI_NO_DISPLAY` set to `"1"`. This way we ensure that we use `Agg` backend and shouldn't come across this error again.
Closes #516
=> FIX: Failure in CICD with plot on matplotlib

doc/source/getting_started/about.rst, doc/source/user_guide/edb_information_queries/get_layout_bounding_box.rst, doc/source/user_guide/excitations/create_circuit_ports_on_component.rst, doc/source/user_guide/excitations/create_coax_port_on_component.rst, doc/source/user_guide/excitations/create_current_source.rst, doc/source/user_guide/excitations/create_edge_port_on_polygon.rst, doc/source/user_guide/excitations/create_port_between_pin_and_layer.rst, doc/source/user_guide/layer_stackup/define_layer_stackup.rst
Some path were using `Resources` in the path when the directory's name is `resources`.
This PR should fix the failing paths.
=> DOCS: Fix path to resoures figures

src/pyedb/dotnet/edb_core/dotnet/primitive.py, src/pyedb/dotnet/edb_core/edb_data/primitives_data.py, tests/legacy/system/test_edb_modeler.py
I've also added an overload method for path and circles which changes respectively the width and the radius with the offset
=> FEAT: added expand method to class PrimitivesDotNet

src/pyedb/dotnet/edb_core/cell/layout.py, src/pyedb/dotnet/edb_core/components.py, src/pyedb/dotnet/edb_core/dotnet/primitive.py, src/pyedb/dotnet/edb_core/layout.py, tests/legacy/system/test_edb_modeler.py
It works also for Voids parts of an existing polygon Added also the property and setter aedt_name
=> FEAT: Get Primitive from an ID.

src/pyedb/dotnet/edb.py, tests/legacy/system/test_edb.py
=> FEAT: Add voids to extent

pyproject.toml
Add pandas as a default dependency and reorder some dependencies in alphabetical order.
Fixes #620.
=> FIX: Add pandas as default dependency

examples/legacy_pyaedt_integration/09_Configuration.py, examples/legacy_standalone/10_GDS_workflow.py, examples/use_configuration/set_up_edb_for_signal_integrity_analysis.py
=> DOCS: Fix example bullet points

src/pyedb/dotnet/edb.py, tests/legacy/system/test_edb_nets.py
Variable renaming and also the trace_net_filters now applies also to padstack definitions.
=> FEAT: Improved auto_parametrize_design method.

.github/workflows/ci_cd.yml
The latest actions/upload-artifact version broke the doc-build job in our CICD.
Until that is fixed, we should pin the action to its previous version: v4.3.4
=> CI: Pin upload-artifact version

.github/workflows/ci_cd.yml
Recently we had to pin the version of the upload artifact, this is no longer required.
=> CI: Revert upload artifact to v4 (unpin)

doc/.vale.ini, doc/source/api/SimulationConfigurationV2.rst, doc/source/api/XmlControlFile.rst, doc/source/api/edb_data/HfssExtentInfo.rst, doc/source/api/edb_data/Utilities.rst, doc/source/api/edb_data/index.rst, doc/source/api/sim_setup_data/data/index.rst, doc/source/api/sim_setup_data/data/sim_setup_info.rst, doc/source/api/sim_setup_data/data/simulation_settings.rst, doc/source/api/sim_setup_data/io/index.rst, doc/styles/Vocab/ANSYS/accept.txt
This PR aims at fixing the documentation style issue that we are currently stacking on the repo.
On top of it, it will convert any new warning to the google rules as an error.
This way, we are sure that external contributors as well as dependabot won't have the CICD failing due to the code-style action while they didn't do any doc modification at all. This is related to the scope of each PR.
=> DOCS: Fix doc style

examples/legacy_pyaedt_integration/03_5G_antenna_example.py, examples/legacy_pyaedt_integration/03_5G_antenna_example_parametrics.py, examples/legacy_pyaedt_integration/04_edb_parametrized_design.py, examples/legacy_pyaedt_integration/09_Configuration.py, examples/legacy_pyaedt_integration/12_edb_sma_connector_on_board.py, examples/legacy_pyaedt_integration/13_edb_create_component.py, examples/legacy_pyaedt_integration/14_edb_create_parametrized_design.py, examples/legacy_pyaedt_integration/15_ac_analysis.py, examples/legacy_standalone/08_CPWG.py, examples/use_configuration/import_material.py, examples/use_configuration/import_ports.py, examples/use_configuration/import_setup_ac.py, examples/use_configuration/import_stackup.py, examples/use_configuration/set_up_edb_for_signal_integrity_analysis.py, src/pyedb/dotnet/application/Variables.py, src/pyedb/dotnet/edb_core/edb_data/primitives_data.py, src/pyedb/edb_logger.py
The one in settings was used in PyAEDT when PyEDB is initialized, so the warning was appearing in PyAEDT. 
I also changed the examples to avoid the warnings.
=> FIX: Replace pyaedt to ansys.aedt.core

src/pyedb/configuration/cfg_operations.py, src/pyedb/configuration/cfg_pin_groups.py, src/pyedb/dotnet/edb_core/cell/layout.py, src/pyedb/dotnet/edb_core/cell/terminal/pingroup_terminal.py, src/pyedb/dotnet/edb_core/modeler.py, tests/legacy/system/test_edb_configuration_2p0.py, tests/legacy/system/test_siwave.py
- EDB configuration. Improved pin group creation and export. 
- pyedb bug fix.
=> FIX: cfg pin group

pyproject.toml
This is a revert from a recent change. The reason for this is that we are having issues with `numpy>=2.` when working on Linux. Unfortunately, the last PR passed because no tests were performed on Linux os.
I'm not extactly sure of why things don't work as expected but here is my idea. When working with Linux, we leverage the libs from `"AnsysEM/v242/Linux64/common/mono/Linux64/lib64"` and also `dotnetcore` / `dotnetcore2` which comes with an embedded `dotnet`. However, this does not work well with `numpy>=2.`. This is probably due to missing symbols / conflicts associated to the libstdc++.so.6. Typically, GLIBCXX_3.4.26 is not found in AEDT's mono libstdc++ making this lib working with `dotnet<=6`.
To avoid breaking a lot of things for users, I propose that we do not allow `numpy>=2.` …
=> BUILD: Remove numpy>=2. compatibility

src/pyedb/configuration/cfg_data.py, src/pyedb/configuration/cfg_padstacks.py, src/pyedb/configuration/configuration.py, src/pyedb/dotnet/edb_core/edb_data/padstacks_data.py, src/pyedb/dotnet/edb_core/general.py, tests/legacy/system/test_edb_configuration_2p0.py, tests/legacy/system/test_edb_padstacks.py
- Add padstack definition import/export per layer capability in edb configuration
- Add workaround to handle antipad and thermal pad missing bug in .net api. 
- Add properties pad_parameters and hole_parameters
- Add set_properties and get_properties to padstack definition
- Methods to convert PascalCase to snake_case, snake_case to PascalCase
=> FEAT: edb configuration padstack

src/pyedb/dotnet/edb_core/cell/primitive/primitive.py, src/pyedb/dotnet/edb_core/layout_validation.py
area method is failing for PadstackInstances
the net_list argument is already used in the same loop. Renamed to avoid issues
=> FIX: Fix disjoint_nets method

.github/workflows/ci_cd.yml
To avoid as much as possible a situation where pyaedt's CICD is no longer working after a release of pyedb, see #800, I'd like to add a job to tests pyaedt in Linux.
=> CI: Add pyaedt linux testing when releasing

.github/labeler.yml, .github/labels.yml, .github/workflows/label.yml
Adds a label associated to the grpc transition. This will help to track changes that need to be added to the grpc changes.
=> CI: Add labeler for grpc transition

src/pyedb/configuration/cfg_components.py, src/pyedb/dotnet/edb_core/cell/hierarchy/component.py, tests/legacy/system/test_edb_components.py, tests/legacy/system/test_edb_configuration_2p0.py
Fix `EDBComponent.ic_die_properties` setter and application of same from EDB configuration files.
Fixes #828
=> FIX: IC Die Properties setter fixes

.pre-commit-config.yaml, doc/source/conf.py, examples/use_configuration/set_up_edb_for_signal_integrity_analysis.py
As title says.
The reason for this change is related to a new major release of precommit where `python_venv` configuration can no longer be used. Since the docformatter is still using it ATM, we should temporarily comment this check.
Note that https://github.com/PyCQA/docformatter/pull/287 fixes the problem and has been merged last week. We are just waiting for a new release.
=> CHORE: Temporary removal of docformatter hook

src/pyedb/dotnet/edb.py
=> FIX: setup types

src/pyedb/dotnet/edb_core/materials.py, tests/legacy/system/test_edb_materials.py
Ensure that users creating material through `pyedb` end up with a material with a permeability equal to `1` instead of `0` (default value retrieved through EDB API).
Closes #827
=> FEAT: Add default value to material permeability

src/pyedb/configuration/cfg_operations.py
Some nets has no primitive. It leads to error.
=> FIX: edb cfg cutout

src/pyedb/configuration/cfg_padstacks.py, src/pyedb/configuration/configuration.py, src/pyedb/dotnet/edb_core/cell/primitive/primitive.py, src/pyedb/dotnet/edb_core/edb_data/primitives_data.py, src/pyedb/dotnet/edb_core/padstack.py, tests/legacy/system/test_edb_modeler.py
- expand method from .net api create a new polygon. It needs to be set to the primitive.
- only polygon can expand. Move expand method to EdbPolygon class
- Remove uittest for Path
- do not export padstack definition by default.
=> FIX: polygon doesn't update after expansion

doc/source/api/CoreEdb.rst, doc/source/api/SimulationConfigurationV2.rst, doc/source/api/edb_data/PrimitivesData.rst, doc/source/api/sim_setup_data/data/settings.rst, doc/source/api/utilities/simulation_setup.rst
@hui-zhou-a While working on a fix to #889 I found typos in class references. This should patch those.
=> DOCS: Correct typos in class names/paths

.github/workflows/ci_cd.yml
The release workflows was failing due to the changes in architecture of pyaedt.
The previous folders `_unittest` and `_unittest_solvers` are no longer existing.
=> CI: Update pyaedt tests jobs

.github/workflows/ci_cd.yml, doc/source/build_breaking_change.rst, src/pyedb/__init__.py, src/pyedb/dotnet/clr_module.py, tests/test_warnings.py
The changes allow one to leverage a dotnet installation at system level.
This is something that we should encourage as using `dotnetcore2` prevents us from providing a conda recipe and also because `dotnetcore2` requires openssl1.1 to be installed. It can't work with newer versions.
=> REFACTOR: Dotnet coreclr loading

src/pyedb/common/nets.py
Introduce import error fences for optional plotting behavior in pyedb.common.nets.CommonNets.plot.
Fixes #925
=> FIX: Introduce import error tests for optionals

.github/workflows/ci_cd.yml, src/pyedb/dotnet/clr_module.py
As title says, see #922 for more information.
Below is the result after calling the same sequences that caused an error previously:
Close #922
=> FIX: DOTNET_ROOT handling with pyaedt

src/pyedb/dotnet/clr_module.py, tests/legacy/unit/test_clr_module.py
As pointed out in https://github.com/ansys/pyedb/pull/924/files#r1870405256, the value that we are passing to `os.environ` is a `Path` instance while it should be `str`. This solves this issue.
@isaacwaldron I'll check that this works correctly when I get back from my trip and make a new release.
=> FIX: Set DOTNET_ROOT with str and not Path

.github/workflows/ci_cd.yml, pyproject.toml, src/pyedb/generic/process.py, tests/legacy/system/test_edb.py
For unknown reason the previous VM stopped working and no fix could be found, a new one was created and it uses standard path for AEDT installation.
I don't know how I succeeded to make all tests to work with the previous VM but, despite all my efforts, I'm no longer able to run test that leverage export_3d_cad aka export_to_hfss, export_to_q3d and export_to_maxwell. The reason is related to Siwave which must be called directly (through /opt/AnsysEM/v242/Linux64/siwave) leading to rendering the UI which is an issue in a non graphical environment.
Note that when using X virtual framebuffer, the tests are just taking too much time...
For the time being I've updated the PR to skip those 3 tests when they are run in linux on CICD. Note that you can still run them if you have a graphic card. …
=> CI: Updates to use the new self-hosted runner

src/pyedb/dotnet/edb_core/components.py
Duplicates PR #962 which was created from a fork.
---
Several times, die designs don't have any component in them.
The code changes made in this PR signifiantly reduces the Component initialization time in this case which thereby reduces the Edb initialization time by ~50% especially when there are >100k Groups in the layout.
This should also speed up EDB initialization time when there are 1000s of components in the design (Ex: Deep trench capacitors in the IC).
=> REFACTOR: Optimize Edb initialization for die designs

tests/legacy/unit/test_edbsiwave.py
=> TEST: Use pytest tmpdir instead of user HOME

.github/workflows/ci_cd.yml
Previous deselection (https://github.com/ansys/pyedb/pull/989) was failing because it must be specified from project root.
I tried it locally and from a folder `src` where I cloned `pyedb`, when I run `pytest pyedb/tests/legacy/unit --deselect=tests/legacy/unit/test_edb.py -vvv` the edb tests are correctly unselected (11 unselected tests)
For more information on that deselection requirement see https://github.com/ansys/pyedb/pull/987 and https://github.com/ansys/pyedb/issues/988
Note that https://github.com/ansys/pyedb/commit/da26422756f2dcf972ab659a4777354e7bf76251 was able to pass the file test that was previously failing.
=> CI: Deselect from project root

src/pyedb/dotnet/edb_core/padstack.py
This pull request added padstack instances selection by start and stop layers in cases where vias belong to different layers but overlap in the same polygon.
Speed up the searching through self.instances.
=> FIX: merge via filtered by start and stop layers

examples/use_configuration/import_sources.py, src/pyedb/configuration/cfg_ports_sources.py, src/pyedb/dotnet/edb_core/cell/primitive/primitive.py, src/pyedb/dotnet/edb_core/edb_data/padstacks_data.py, tests/legacy/system/test_edb_configuration_2p0.py
- Move _em_proerties to Primitive class, since it is accessible for all primitives not only padstack.
- EDB API has a bug in equipotential region. The workaround is to create a primitive and make it equipotential region
- New feature in edb config. The user is able to define an equipotential region for sources with point terminals.
- Deleted some redundant lines
=> FEAT: Edb cfg equipotential

src/pyedb/dotnet/edb_core/cell/layout.py, src/pyedb/dotnet/edb_core/edb_data/nets_data.py
Sometimes Primitives contains empty objects (probably after boolean operations). This cause the casting to fail.
=> FIX: Primitive casting

src/pyedb/configuration/cfg_ports_sources.py
Create the net is net from cfg file doesn't exist in edb
=> FIX: edb import coordiante circuilt port

src/pyedb/dotnet/database/components.py, tests/legacy/system/test_edb.py
Fix create_port_on_pins with multiple positive pins, an incorrect conditional was resulting in the creation of pin ports instead of pin group ports in this case.
=> FIX: Circuit port creation on multiple pins

.github/workflows/ci_cd.yml
=> CI: Add mandatory token to Github release job

src/pyedb/__init__.py, src/pyedb/dotnet/clr_module.py
When `DOTNET_ROOT` is set, pass the selected candidate as the `runtime_spec` argument of `pythonnet.load` instead of the
`runtime_config` argument.  This avoids a failure since the candidates are selected from a list of `DotNetCoreRuntimeSpec` instances.
Fixes #1306
=> FIX: Pass runtime candidate as runtime_spec instead of runtime_config when DOTNET_ROOT is set

src/pyedb/grpc/database/definition/materials.py, tests/grpc/system/test_edb_materials.py, tests/grpc/system/test_edb_stackup.py
Update unit tests to be compatible with upcoming pyedb-core pre-release package v0.2.0.dev5
=> FIX: Update unit tests to be compatible with upcoming pyedb-core pre-release package

src/pyedb/grpc/edb.py, tests/grpc/system/test_edb.py
This PR is adding import - export layout component. This feature is only supported with gRPC API.
=> FEAT: Adding import - export layout component

pyproject.toml
As title says.
Close #1337 
@svandenb-dev Pydantic is used for `Material` related classes. I assumed that it would be used in other classes but that is not the case. If you don't plan to use it, let me know and we could just remove this dependency & refactor the material class to work with something builtin.
=> BUILD: Bump pydantic upper bound to <2.12

src/pyedb/configuration/cfg_common.py, src/pyedb/configuration/cfg_data.py, src/pyedb/configuration/configuration.py, tests/legacy/system/conftest.py, tests/legacy/system/test_edb_configuration_2p0.py
=> FEAT: edb cfg export variables

.github/workflows/ci_cd.yml
As title says. Avoid using non pinned version of `vtk-osmesa` to prevent supply chain attack.
=> CI: Pin vtk-osmesa version

pyproject.toml
I think the handling of the `ansys-edb-api` package should be left to `ansys-edb-core` since we don't directly leverage the former package. Avoiding this will also help with dependency resolution conflicts in the pyansys meta package.
If there is something wrong with the version of the `ansys-edb-api`, an issue should be opened [here](https://github.com/ansys/pyedb-core/issues) so that the concerned maintainers handle the dependency issue.
FYI, here is the kind of issues that we are having:
```
The conflict is caused by:
pyedb 0.56.dev0 depends on ansys-api-edb>=0.2.0
ansys-edb-core 0.3.0.dev0 depends on ansys-api-edb==0.2.dev6
```
The maintainers of `ansys-edb-core` should be doing a new release to correctly manage the versions requirements with `ansys-api-edb` soon :) Pinging @drewm102 …
=> BUILD: Remove ansys-edb-api dependency

src/pyedb/generic/data_handlers.py, src/pyedb/generic/filesystem.py, src/pyedb/generic/general_methods.py, src/pyedb/grpc/rpc_session.py, tests/conftest.py
This PR provides an alternative syntax using the ``secrets`` module instead of ``random`` in all instances where the latter was used. The changes introduced therefore make it possible to avoid using the ``random`` module throughout the entire ``pyedb`` project.
The motivation for this update can be read from [here](https://docs.python.org/3/library/secrets.html): "``secrets`` should be used in preference to the default pseudo-random number generator in the ``random`` module, which is designed for modelling and simulation, not security or cryptography".
=> REFACTOR: Replace ``random`` by ``secrets`` for random number generation and sampling

SECURITY.md
This PR is adding a ``SECURITY.md`` file based on the model provided [here](https://github.com/ansys-internal/pyansys-maintenance-automation/tree/main/scripts/file_references).
This file is placed at the root of the repository and complemented by the license header used elsewhere in the project.
Close #1316.
=> CHORE: Adding ``SECURITY.md`` file

.github/workflows/ci_cd.yml
Updates to the latest stable version for `vtk-osmesa` and forces the use of ``--index-url``.
=> FEAT: update vtk-osmesa version 9.3.1
